### ISSUE TITLE
needs documentation

### ISSUE THREAD

**Issue by zspecza** [caspervonb/node-rdbg#1]
Since this is one of the moving parts of [Amok](https://github.com/caspervonb/amok), it will need some documentation - even just a small file that explains what this does, why it exists, and how it does it's thang would suffice

**Comment by caspervonb** [comment]
So, this is supposed to become an abstraction layer for a subset of the different protocols, right now its only a tiny wrapper around some of the protocol action we need for Amok

**Comment by ganarajpr** [comment]
Have you considered using https://github.com/cyrus-and/chrome-remote-interface ? It should speed up your development ? 

Any reason you are implementing this again ?

**Comment by caspervonb** [comment]
> Have you considered using https://github.com/cyrus-and/chrome-remote-interface?
> It should speed up your development ?

I did use it for the first iteration, basically i wanted a more programmatic, protocol independent API so it can be iterated on based on requirements and a clean API rather than how the chrome protocol looks.

When this eventually supports more protocols than just chrome, I don't want to pull in multiple dependencies that depend on `ws`, that package is huge and takes forever to build.

Lastly, this is just a bit of personal bias but the API of `chrome-remote-interface` is a bit iffy, it can be better.

Had a hard time getting it to do what i wanted on connection failure
